server:
  port: 5000

spring:
  config:
    import:
      - 'aws-parameterstore:/yologram/service/application_${spring.profiles.active}/'
      - 'aws-parameterstore:/yologram/service/${spring.application.name}_${spring.profiles.active}/'
  cloud:
    aws:
      credentials:
        instance-profile: true

core:
  master:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://service-staging.c56as866g5sl.ap-northeast-2.rds.amazonaws.com:3306/yologram?useUnicode=true&charset=utf8mb4&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul&useSSL=false&rewriteBatchedStatements=true
      username: yologram_api
      hikari:
        pool-name: hikaricp.service-staging.yologram.master
        max-lifetime: 1800000 # 30m
        minimum-idle: 1
        maximum-pool-size: 1
  slave:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://service-staging.c56as866g5sl.ap-northeast-2.rds.amazonaws.com:3306/yologram?useUnicode=true&charset=utf8mb4&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul&useSSL=false
      username: yologram_api
      hikari:
        pool-name: hikaricp.service-staging.yologram.slave
        max-lifetime: 1800000 # 30m
        minimum-idle: 1
        maximum-pool-size: 1