server:
  port: 5000

spring:
  config:
    import:
      - 'aws-parameterstore:/yologram/service/application_${spring.profiles.active}/'
      - 'aws-parameterstore:/yologram/service/${spring.application.name}_${spring.profiles.active}/'
  cloud:
    aws:
      credentials:
        instance-profile: true
#  data:
#    redis:
#      # cluster:
#      #   nodes: localhost:6379
#      host: localhost
#      port: 6379
#      repositories:
#        enabled: false

core:
  master:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://serivce-prod.cv4imowma8xe.ap-northeast-2.rds.amazonaws.com:3306/yologram?useUnicode=true&charset=utf8mb4&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul&useSSL=false&rewriteBatchedStatements=true
      username: yologram_api
      hikari:
        pool-name: hikaricp.service-prod.yologram.master
        max-lifetime: 1800000
        minimum-idle: 1
        maximum-pool-size: 10
  slave:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://serivce-prod.cv4imowma8xe.ap-northeast-2.rds.amazonaws.com:3306/yologram?useUnicode=true&charset=utf8mb4&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul&useSSL=false
      username: yologram_api
      hikari:
        pool-name: hikaricp.service-prod.yologram.slave
        max-lifetime: 1800000
        minimum-idle: 1
        maximum-pool-size: 10